Create performance section issue #13
SergeyKharkovshchenko/lubimovka-teamwork pull request #36
Opened 2022-10-24 02:20 UTC by Ori-wiki

Сверстал performance-section
Карточку со спектаклем сделал отдельным бэм-блоком "card"
И добавил картинки в папку /images/performance-section в формате .jpg
Может, какие-нибудь названия классов поменять?

2022-10-24 06:25 UTC, ArtyemSavchenko commented
>Может, какие-нибудь названия классов поменять?
я бы название card уточнил бы а-ля card-performance. у нас на этой же странице и наверняка на других страницах тоже есть карточки, чтобы с неймингом не пересекаться.

2022-10-24 07:32 UTC, ArtyemSavchenko requested changes
В целом мне понравилась верстка.
Я бы еще подумал о центрировке карточек в мобильной версии, чтобы они не размазывались по горизонтали на разрешении около 700px. И пару моментов откомментил, оставил вопрос про проценты в марджинах, мне действительно интересно.

2022-10-24 07:32 UTC, ArtyemSavchenko commented on index.html
> +            <h3 class="card__title heading--medium">Про линя</h3>
с модификатором heading--medium нужен и сам блок heading, там основные стили прописаны. аналогично с body-text далее по коду
можно в ВС коде поиск и замену сделать `heading--medium` на `heading heading--medium`
для опций замены надо кнопку слева нажать
<img width="329" alt="image" src="https://user-images.githubusercontent.com/105359320/197462108-a12dd97c-3239-49f6-b0bd-1a2c3882fc6a.png">

2022-10-24 07:32 UTC, ArtyemSavchenko commented on blocks/performance-section/performance-section.css
> +  margin: 0 0 6% 6%;
зачем вы проценты используете в марджинах? не первый раз вижу. это ж динамические и неконтролируемые величины. 
в хтмл файле коммент оставлю по поводу заголовка.

2022-10-24 07:32 UTC, ArtyemSavchenko commented on index.html
> +      <h2 class="section-title performance-section__section-title">Заголовок блока<br>с тремя и более<br>спектаклями</h2>
я под этот заголовок сделал классы `heading` (без модификаторов) и `page__title` - в нем геометрия горизонтальных отступов. 
останется только прописать вертикальный отступ в `performance-section__section-title` 34px для мобилы и 75px для десктопа, потому что дизайнер похоже был очень воодушевлен, и сделал в каждом блоке свои отступы по вертикали.

2022-10-24 07:32 UTC, ArtyemSavchenko commented on blocks/card/card.css
> +.card__button:not(:last-child) {
крутой прием 😎

2022-10-24 09:20 UTC, Ori-wiki commented on blocks/card/card.css
> +.card__button:not(:last-child) {
Спасибо за крутое ревью.

2022-10-24 09:40 UTC, Ori-wiki commented on blocks/performance-section/performance-section.css
> +  margin: 0 0 6% 6%;
Ну, тут я сделал просто, как в другом блоке, чтобы были одинаковые отступы
про "page-title" увидел
круто, только на высоких разрешениях другой отсуп по горизонтали

2022-10-24 11:41 UTC, SergeyKharkovshchenko approved these changes

2022-10-24 11:50 UTC, ArtyemSavchenko commented on blocks/performance-section/performance-section.css
> +  margin: 0 0 6% 6%;
можно пример?
я брал заголовок в макс. 720 пикселей (половина от максимальных 1440), и ставил посередине. вроде логично выходит.
<img width="734" alt="image" src="https://user-images.githubusercontent.com/105359320/197518989-b3762c47-8f8c-4bff-992a-eb823a0dfbef.png">

2022-10-24 12:27 UTC, Ori-wiki commented on blocks/performance-section/performance-section.css
> +  margin: 0 0 6% 6%;
ага, не сразу понял, что оно так работает, потому что у меня класс  "section-title" перебивал "page-title"
![image](https://user-images.githubusercontent.com/92172416/197524441-b94cea4f-62cb-40eb-804e-0844e33c2f5a.png)

2022-10-26 07:16 UTC, ArtyemSavchenko approved these changes
Цвет на переменную заменить и можно заливать

Пожалуйста, не забывайте после заливки в дев карточку в Projects переносить и закрывать issue там же

2022-10-26 07:16 UTC, ArtyemSavchenko commented on blocks/card-performance/card-performance.css
> +  border-bottom: 1px solid #242424;
по-моему этот цвет у нас в переменных лежит. --base-color или как-то так.

2022-10-26 07:58 UTC, merged