исправил кнопки на ссылки, исправил возможность переполнения текстом з…
SergeyKharkovshchenko/lubimovka-teamwork pull request #57
Opened 2022-11-11 07:46 UTC by LethL

…аголовков карточек

2022-11-12 12:26 UTC, ArtyemSavchenko requested changes
Переименуй под БЭМ класс и заливай.

2022-11-12 12:26 UTC, ArtyemSavchenko commented on index.html
> +            <h3 class="heading heading--small heading__play-section">Конкретные разговоры пожилых супругов ни о чём</h3>
нейминг.
heading__play-section -> play-section__heading
заголовок как элемент блока, там геометрия.

2022-11-13 04:37 UTC, Ori-wiki approved these changes

2022-11-15 09:45 UTC, LethL commented on index.html
> +            <h3 class="heading heading--small heading__play-section">Конкретные разговоры пожилых супругов ни о чём</h3>
done

2022-11-15 09:45 UTC, merged